spring:
  application:
    name: cims-backend

  datasource:
    url: jdbc:mysql://localhost:3306/cims_schema
    username: root
    password: root

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: zainu3x007@gmail.com
    password: favctetycskbcmbe

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true